config/routes.rb
Rails.application.routes.draw do
  get 'ingredients/index'

  resources :cocktails do
    resources :doses, only: [:new, :create, :show]
  end
  resources :doses, only: [:destroy]
  resources :ingredients, only: [:index]
  root to: 'cocktails#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  mount_uploader :photo, PhotoUploader
  has_many :doses, dependent: :destroy, inverse_of: :cocktail
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true
  accepts_nested_attributes_for :doses, reject_if: :all_blank, allow_destroy: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail, inverse_of: :doses
  validates :cocktail, presence: true, uniqueness: {scope: :ingredient}
  validates :ingredient, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  def edit
    @cocktail = Cocktail.find(params[:id])
  end

  def update
    @cocktail = Cocktail.find(params[:id])
    @cocktail.update(cocktail_params)
    redirect_to @cocktail
  end

  def index
    @cocktails = Cocktail.all
    @random = Cocktail.order('RANDOM()').limit(1).first
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
    @ingredients = Ingredient.all.order("name asc")
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def destroy
    @cocktail = Cocktail.find(params[:id])
    @cocktail.destroy
    redirect_to cocktails_path
  end

  protected

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo, :photo_cache, doses_attributes: [:ingredient_id, :description, :id])
  end

end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @ingredients = Ingredient.all
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.delete
    redirect_to cocktails_path
  end

  protected

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all.order("name asc")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/views/cocktails/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url( <%=image_path('cocktails.jpg')%>);">
  <div class="banner-content">
    <h1>Find yourself in a glass</h1>
    <p>Search some of our great cocktail recipes</p>
    <%= link_to "Pick A Random Cocktail", cocktail_path(@random), class: "btn btn-primary btn-lg" %>
  </div>
</div>

app/views/cocktails/_dose_fields.html.erb
<div class="form-inline">
<%= f.input :ingredient_id, collection: Ingredient.all.order("name asc"), input_html: {class: 'label-margin'}, label_html: { class: 'form-box' } %>
<%= f.input :description, label_html: { class: 'form-box' }, input_html: {class: 'label-margin'} %>
</div>

app/views/cocktails/_form.html.erb
<%= simple_form_for @cocktail do |f| %>
  <% if @cocktail.errors.any? %>
    <div id="error-explanation">
      <ul>
      <% @cocktail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :name, label: 'Cocktail Name', placeholder: 'Margarita' %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <h3>Add a dose below</h3>
  <div id="doses">
    <%=  f.simple_fields_for :doses do |dose|%>
      <%= render 'dose_fields', f: dose %>
    <% end %>
    <div class="links">
      <%= link_to_add_association 'Add Dose', f, :doses, class: "btn btn-primary"%>
      <%= f.submit class: "btn btn-primary text-right" %>
    </div>
  </div>

<% end %>

app/views/cocktails/edit.html.erb
<div class="wrapper">
  <div class="form-container">
    <h1 class="text-center">Edit A Cocktail</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/cocktails/index.html.erb
<%= render 'banner' %>
<div class="container text-center">
  <h1>Cocktails</h1>
  <% if @cocktails.any? %>
  <div class="row">
    <% @cocktails.each do |cocktail| %>
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
      url('<%= cl_image_path cocktail.photo, crop: :fill %>'); background-size: cover;">
      <div class="card-description">
        <h2><%= cocktail.name %></h2>
      </div>
      <a class="card-link" <%= link_to "", cocktail_path(cocktail) %></a>
    </div>
  </div>
  <% end %>
  <% end %>
</div>
<div class="add-restaurant">
  <%= link_to "Add a new cocktail", new_cocktail_path, class: "btn btn-primary" %>
</div>
</div>

app/views/cocktails/new.html.erb
<%= simple_form_for @cocktail do |f| %>
  <% if @cocktail.errors.any? %>
    <div id="error-explanation">
      <ul>
      <% @cocktail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :name, label: 'Cocktail Name', placeholder: 'Margarita' %>
  <h3>Add Doses</h3>
  <div id="doses">
    <%=  f.simple_fields_for :doses do |dose|%>
      <%= render 'dose_fields', f: dose %>
    <% end %>
    <div class="links">
     <%= link_to_add_association 'add dose', f, :doses%>
    </div>
  </div>
  <%= f.submit %>
<% end %>

app/views/cocktails/show.html.erb
<div class="main-container">
  <div class="text-container">
    <h1><%= @cocktail.name %></h1>
    <% @cocktail.doses.each do |dose| %>
    <p><%= dose.ingredient.name %>, <%= dose.description %></p>
    <% end %>
    <div class="buttons">
      <p>
        <%= link_to "Edit your cocktail", edit_cocktail_path, class: "btn btn-primary" %>
        <%= link_to "Delete Cocktail", cocktails_path, method: :destroy, class: "btn btn-primary" %>
        <%= link_to "Back", cocktails_path, class: "btn btn-primary" %>
      </p>
    </div>
  </div>
  <div id="cocktail-photo">
    <%= cl_image_tag @cocktail.photo %>
  </div>
</div>

app/views/doses/new.html.erb
<h1>Add a dose</h1>
<%= simple_form_for @dose do |f| %>
  <% if @dose.errors.any? %>
    <div id="error-explanation">
      <ul>
      <% @dose.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :ingredient_id, label: 'Ingredient', collection: @ingredients %>
  <%= f.input :description, label: 'Description' %>
  <%= f.submit %>
<% end %>

app/views/doses/show.html.erb
<h1>Doses#show</h1>
<p>Find me in app/views/doses/show.html.erb</p>

app/views/ingredients/index.html.erb
<div class="container">
  <div class="ingredients-container">
    <h1>Ingredients</h1>
    <ul class="list-inline">
      <% if @ingredients %>
      <% @ingredients.each do |ingredient| %>
      <li> <%= ingredient.name %> </li>
      <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo-2.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "Cocktails", cocktails_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "Ingredients", ingredients_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "avatar.jpg", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>